### ISSUE TITLE
ImportError: No module named PyPDF2

### ISSUE THREAD

**Issue by dainius-sileika** [mullinscr/pocketmod-creator#1]
`% python pocketmod_creator.py dragon.pdf
Traceback (most recent call last):
  File "pocketmod_creator.py", line 35, in <module>
    from PyPDF2 import PdfFileReader, PdfFileWriter
ImportError: No module named PyPDF2
`
And yet:

`% pip3 install PyPDF2
Requirement already satisfied: PyPDF2 in /usr/local/lib/python3.7/site-packages (1.26.0)`

FWIW, I'm running OSX and have python installed via brew. 

TIA,

-D

**Comment by mullinscr** [comment]
- Are you using Visual Studio Code? (If so make sure you are executing the code with the correct version of python)
- Do you have multiple versions of Python installed? Or Anaconda?

In any case you could try the following:

`python3.7 -m pip install PyPDF2` to install it; or
`python3.7 -m pip list` to check if it is actually an available module.

**Comment by dainius-sileika** [comment]
Thanks for the quick reply!

% python3.7 -m pip list
Package    Version
---------- -------
pip        19.2.3 
PyPDF2     1.26.0 
setuptools 41.4.0 
wheel      0.33.6 

*but*--when I tried %python3.7 pocketmod_creator.py input.pdf it worked, so looks like it might very well be multiple versions of python. Issue closed, I guess!

**Comment by mullinscr** [comment]
No worries. Glad you got it working.

**Comment by alvarova** [comment]
> python3.7 -m pip install PyPDF2

Excelent! It works for me. I have 2 version, and when i list modules, never install for last python version. Thanks a lot.
